apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'

android {
    namespace="com.lot.kes.CartridgeQuest"
    buildFeatures.prefab true
    compileSdkVersion 36
    ndkVersion '29.0.14206865'
    buildToolsVersion '35.0.0'
    defaultConfig {
        applicationId "com.lot.kes.CartridgeQuest"
        minSdkVersion 24
        //noinspection OldTargetApi
        targetSdk 33
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                cppFlags ""
                arguments '-DANDROID_STL=c++_shared',
                          '-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON',
                          '-DOPENAL_DIR=/home/jrs0ul/libopenal',
                          '-DOGG_VORBIS_DIR=/home/jrs0ul/oggvorbis'
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"

        }
    }
    ndkVersion '29.0.14206865'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"

    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.core:core:1.17.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.games:games-activity:4.0.0'
    implementation 'androidx.core:core-ktx:1.17.0'
    implementation 'androidx.compose.runtime:runtime-saved-instance-state:1.0.0-alpha11'
    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
}
