import os
import sys

OBJ_DIR = os.path.join(os.getcwd(), 'obj/');
env = Environment(ENV=os.environ,
                  CCFLAGS=['-O3','-Wall'],
                  OBJPREFIX = OBJ_DIR)

#Windblows
if sys.platform == 'win32':
    Tool('mingw')(env)
    env.Append(LIBS = ['mingw32','SDL2main', 'SDL2', 'OpenGL32',
		        'imagehlp', 'dxguid', 'dxerr8',
			'oleaut32', 'shell32', 'version', 'uuid',
                       'openal32', 'vorbisfile', 'ole32', 'imm32', 'user32', 'gdi32', 'winmm', 'dinput8', 'vorbis', 'ogg',])
else: #Mac OS X
    if sys.platform == 'darwin':
        env['FRAMEWORKS'] = ['Cocoa', 'SDL2', 'OPENGL', 'OpenAL','vorbis', 'Ogg']
        env.Append(LIBS = [ 'iconv', 'pthread'])
    else: #Linux
        env.Append(LIBS = ['SDL2','GL', 'GLU', 'openal', 'vorbisfile',
                           'ogg', 'pthread'])


env.Program(target = "DUDED", 
            source = ["src/main.cpp",
                      "src/CIniFile.cpp",
                      "../src/map.cpp",
                      "../src/MapGenerator.cpp",
                      "../src/TextureLoader.cpp",
                      "../src/Image.cpp",
                      "../src/Dude.cpp",
                      "../src/Usefull.cpp",
                      "../src/gui/Text.cpp",
                      "../src/Vectors.cpp",
                      "../src/Shader.cpp",
                      "../src/SDLVideo.cpp",
                      "../src/Xml.cpp",
                      "../src/BulletContainer.cpp",
                      "../src/OSTools.cpp",
                      "../src/Decal.cpp",
                      "src/Button.cpp",
                      "src/Utils.cpp",
                      "../src/Matrix.cpp",
                      "../src/ShaderProgram.cpp",
                      "../src/Extensions.cpp"
                      ]
            )

