#pragma once

enum NetworkCommands
{
    NET_NOP = 0,

    NET_CLIENT_MSG_CONNECT = 1,
    NET_CLIENT_MSG_CHARACTER_DATA,
    NET_CLIENT_MSG_WEAPON_SHOT,
    NET_CLIENT_MSG_ITEM,
    NET_CLIENT_MSG_DOOR,
    NET_CLIENT_MSG_NEXT_LEVEL,
    NET_CLIENT_MSG_MELEE_ATTACK,
    NET_CLIENT_MSG_QUIT,
    NET_CLIENT_MSG_COOP_RESURRECT,
    NET_CLIENT_MSG_GAME_EQUIPED,
    NET_CLIENT_MSG_PONG = 20,

    NET_SERVER_MSG_CHARACTER_DATA,
    NET_SERVER_MSG_REMOVE_CHARACTER,
    NET_SERVER_MSG_SERVER_INFO,
    NET_SERVER_MSG_MAP_DATA,
    NET_SERVER_MSG_KILL_CHARACTER,
    NET_SERVER_MSG_FRAG,
    NET_SERVER_MSG_WEAPON_SHOT,
    NET_SERVER_MSG_ITEM,
    NET_SERVER_MSG_DOOR,
    NET_SERVER_MSG_NEW_ITEM,
    NET_SERVER_MSG_MELEE_ATTACK,
    NET_SERVER_MSG_PING,
    NET_SERVER_MSG_SHUTTING_DOWN,
    NET_SERVER_MSG_SYNC_TIMER,
    NET_SERVER_MSG_COOP_GAME_OVER,
    NET_SERVER_MSG_COOP_RESURRECT,
    NET_SERVER_MSG_GAME_EQUIPED
};

